services:
  nextjs-app:
    container_name: frontend_container  # Name of the container for easy reference
    build:
      context: .  # The current directory is used as the build context
      dockerfile: Dockerfile  # Use the Dockerfile in the current directory for the build
    ports:
      - "3000:3000"  # Expose port 3000 on the container and map it to port 3000 on the host
    volumes:
      - .:/app  # Mount the current directory (your app files) to the /app directory inside the container
    environment:
      - CHOKIDAR_USEPOLLING=true  # Enable polling for file changes (required in Docker to detect file changes)
      - WATCHPACK_POLLING=true     # Enable watchpack polling to support file watching inside Docker
    stdin_open: true  # Keep the standard input open, allows interactive access to the container
    tty: true  # Allocates a pseudo-TTY, useful for debugging and keeping the terminal interactive